name: "k8s connect action"
description: "This action allows connecting and performing action on a pass-culture kubernetes cluster through a bastion VM (tinyproxy)"
inputs:
  cluster_scope:
    description: The scope of the cluster (metier/data/infra)
    required: true
  cluster_environment:
    description: The environment of the cluster (prod/ehp)
    required: true
  api_token_github:
    description: The Github Token API to use to clone the pc-k8s-connect repo
    required: true
  pc_k8s_connect_version:
    description: The revision of the pc-k8s-connect script to use
    required: false
    default: main
  pc_firestore_version:
    description: The revision of the pc-firestore script to use
    required: false
    default: 0.1.0

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: pass-culture/pc-connect
        path: ${{ github.workspace }}/pc-k8s-connect
        token: ${{ inputs.api_token_github }}
        ref: ${{ inputs.pc_k8s_connect_version }}

    - name: Download pc-firestore-cli binary
      shell: bash
      run: |
        export ARCH=$(dpkg --print-architecture)
        asset_id=$(curl -s -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ inputs.api_token_github }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/pass-culture/pc-firestore-cli/releases | jq -r '.[].assets[] | select(.name=="pc-firestore-cli_${{ inputs.pc_firestore_version }}_linux_'${ARCH}'.tar.gz") | .id')
        curl -L \
        -H "Accept: application/octet-stream" \
        -H "Authorization: Bearer ${{ inputs.api_token_github }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/pass-culture/pc-firestore-cli/releases/assets/$asset_id -o pc-firestore-cli.tar.gz
        tar -xzvf pc-firestore-cli.tar.gz
        chmod +x pc-firestore-cli
        mkdir bin
        mv pc-firestore-cli bin/pc-firestore-cli
        echo "$PWD/bin" >> $GITHUB_PATH

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v2"
      with:
        install_components: "gke-gcloud-auth-plugin,kubectl"

    - name: "Connect to cluster"
      shell: bash
      run: |
        ${{ github.workspace }}/pc-k8s-connect/pc-k8s-connect -s ${{ inputs.cluster_scope }} -e ${{ inputs.cluster_environment }}
