name: actionlint-check
description: "Action to setup and run actionlint"
inputs:
  version:
    description: "actionlint version"
    default: "0.1"
    required: false

runs:
    using: "composite"
    steps:
        - name: setup
          uses: actions/checkout@v6
        
        - name: "Install actionlint"
          env:
            VERSION: ${{ inputs.version }}
          shell: bash
          run: |
            env
            curl -sSL -o actionlint.tar.gz https://api.github.com/repos/pass-culture/actionlint/releases/assets/actionlint_$VERSION_linux_amd64.tar.gz
            tar -zxvf actionlint.tar.gz
            ls
