name: "pcapi-pre-migration"
description: "This composite action executes pre-migration on a given pcapi environment"
inputs:
  environment:
    required: true
    description: pcapi environment to target
  app_version:
    required: true
    description: pcapi image version
  migration_type:
    required: true
    description: "pre for pre-migrations and post for post-migrations"
  artifact_registry:
    required: true
    default: europe-west1-docker.pkg.dev/passculture-infra-prod/pass-culture-artifact-registry
runs:
  using: "composite"
  steps:
    - name: "Play pre-migrations"
      if: inputs.migration_type == 'pre'
      shell: bash
      run: |
        set -e
        VERSION="$APP_VERSION"
        export ENVIRONMENT="$ENVIRONMENT"
        IMAGE="$ARTIFACT_REGISTRY/pcapi"
        export IMAGE="${IMAGE}:${VERSION}"
        export DATE="$(date +"%Y-%m-%d--%H-%M-%S")"
        JOB_NAME="pre-upgrade-${DATE}"
        envsubst < "$ACTION_PATH/pre-upgrade-job.yaml" | kubectl -n "$ENVIRONMENT" apply -f -
        # kubectl logs returns 0 if pod is pending because of lack of resource so we use a more elaborate condition
        kubectl wait -n "$ENVIRONMENT" --for=jsonpath='{.status.ready}'=1 "jobs/${JOB_NAME}" --timeout=300s
        # Next lines assume that job's backoffLimit is 0
        kubectl logs -n "$ENVIRONMENT" -f "jobs/${JOB_NAME}"
        kubectl wait -n "$ENVIRONMENT" --for=condition=complete "jobs/${JOB_NAME}" --timeout=120s || kubectl wait -n "$ENVIRONMENT" --for=condition=failed "jobs/${JOB_NAME}" --timeout=120s # Sanity check that the job is over
        failure=$(kubectl get -n "$ENVIRONMENT" "jobs/${JOB_NAME}" -o=jsonpath='{.status.conditions[?(@.type=="Failed")].status}') # Did the job fail or not so we can give correct return code
        if [[ "$failure" == "True" ]]
        then
          exit 1
        else
          exit 0
        fi
      env:
        APP_VERSION: ${{ inputs.app_version }}
        ENVIRONMENT: ${{ inputs.environment }}
        ARTIFACT_REGISTRY: ${{ inputs.artifact_registry }}
        ACTION_PATH: ${{ github.action_path }}

    - name: "Play post-migrations"
      if: inputs.migration_type == 'post'
      shell: bash
      run: |
        set -e
        VERSION="$APP_VERSION"
        export ENVIRONMENT="$ENVIRONMENT"
        IMAGE="$ARTIFACT_REGISTRY/pcapi"
        export IMAGE="${IMAGE}:${VERSION}"
        export DATE="$(date +"%Y-%m-%d--%H-%M-%S")"
        JOB_NAME="post-upgrade-${DATE}"
        envsubst < "$ACTION_PATH/post-upgrade-job.yaml" | kubectl -n "$ENVIRONMENT" apply -f -
        # kubectl logs returns 0 if pod is pending because of lack of resource so we use a more elaborate condition
        kubectl wait -n "$ENVIRONMENT" --for=jsonpath='{.status.ready}'=1 "jobs/${JOB_NAME}" --timeout=300s
        # Next lines assume that job's backoffLimit is 0
        kubectl logs -n "$ENVIRONMENT" -f "jobs/${JOB_NAME}"
        kubectl wait -n "$ENVIRONMENT" --for=condition=complete "jobs/${JOB_NAME}" --timeout=120s || kubectl wait -n "$ENVIRONMENT" --for=condition=failed "jobs/${JOB_NAME}" --timeout=120s # Sanity check that the job is over
        failure=$(kubectl get -n "$ENVIRONMENT" "jobs/${JOB_NAME}" -o=jsonpath='{.status.conditions[?(@.type=="Failed")].status}') # Did the job fail or not so we can give correct return code
        if [[ "$failure" == "True" ]]
        then
          exit 1
        else
          exit 0
        fi
      env:
        APP_VERSION: ${{ inputs.app_version }}
        ENVIRONMENT: ${{ inputs.environment }}
        ARTIFACT_REGISTRY: ${{ inputs.artifact_registry }}
        ACTION_PATH: ${{ github.action_path }}
