name: "Setup safe-chain"
description: "This action installs safe-chain in a specific version."
inputs:
  version:
    type: string
    required: true
    default: "1.2.2"
  checksum:
    type: string
    required: true
    description: "SHA256 hash of the safe-chain binary file."
    default: "db58cbdebb132f3172cd872ef1a3de407cd59d9fe16ce058f87ab43a4b49f799"

runs:
  using: "composite"
  steps:
    - name: setup
      uses: actions/checkout@v4

    - name: "Render manifests"
      shell: bash
      run: |
        set -e
        if ! [ -x "$(command -v curl)" ]; then
          sudo apt update && sudo apt install -qy curl
        fi
        INSTALL_DIR="${HOME}/.safe-chain/bin"
        REPO_URL="https://github.com/AikidoSec/safe-chain"

        error() {
          msg="$1"
          exit_code=$2

          echo "$msg"
          echo "Contact cybersecurite@passculture.app to investigate. Error code $exit_code."
          exit $exit_code
        }

        # Detect OS
        detect_os() {
            case "$(uname -s)" in
                Linux*)     echo "linux" ;;
                Darwin*)    echo "macos" ;;
                *)          error "Unsupported operating system: $(uname -s)" 101 ;;
            esac
        }

        # Detect architecture
        detect_arch() {
            case "$(uname -m)" in
                x86_64|amd64)   echo "x64" ;;
                aarch64|arm64)  echo "arm64" ;;
                *)              error "Unsupported architecture: $(uname -m)" 102 ;;
            esac
        }

        # Download file
        download() {
            url="$1"
            dest="$2"

            curl -fsSL "$url" -o "$dest" || error "Failed to download from $url" 103
        }

        # Check file integrity
        check_file() {
            file="$1"

            hash=$(sha256sum $file | awk '{ print $1 }')

            if [ "$hash" != "$CHECKSUM" ]; then
                error "Invalid checksum. Got $hash ; expected $CHECKSUM Exiting." 104
            fi
            echo "File integrity validated"
        }

        # Main installation
        main() {

            # Build installation message
            INSTALL_MSG="Installing safe-chain ${VERSION}"

            echo "$INSTALL_MSG"

            # Detect platform
            OS=$(detect_os)
            ARCH=$(detect_arch)
            BINARY_NAME="safe-chain-${OS}-${ARCH}"

            echo "Detected platform: ${OS}-${ARCH}"

            # Create installation directory
            if [ ! -d "$INSTALL_DIR" ]; then
                echo "Creating installation directory: $INSTALL_DIR"
                mkdir -p "$INSTALL_DIR" || echo "Failed to create directory $INSTALL_DIR"
            fi

            # Download binary
            DOWNLOAD_URL="${REPO_URL}/releases/download/${VERSION}/${BINARY_NAME}"
            TEMP_FILE="$(mktemp)"

            echo "Downloading from: $DOWNLOAD_URL"
            download "$DOWNLOAD_URL" "$TEMP_FILE"
            check_file "$TEMP_FILE"

            # Rename and make executable
            FINAL_FILE="${INSTALL_DIR}/safe-chain"
            mv "$TEMP_FILE" "$FINAL_FILE" || error "Failed to move $TEMP_FILE to $FINAL_FILE" 105
            chmod +x "$FINAL_FILE" || error "Failed to make $FINAL_FILE executable" 106

            echo "Binary installed to: $FINAL_FILE"

            # Build setup command based on arguments
            SETUP_CMD="setup-ci"
            SETUP_ARGS="--include-python"

            # Execute safe-chain setup
            echo "Running safe-chain $SETUP_CMD $SETUP_ARGS..."
            if ! "$FINAL_FILE" $SETUP_CMD $SETUP_ARGS; then
                error "safe-chain was installed but setup encountered issues." 107
            fi

            # Add config to remove cooldown (temp fix to avoid break CI)
            mkdir ~/.aikido || error "Could not create dir ~/.aikido" 108
            echo '{"minimumPackageAgeHours": 0}' > ~/.aikido/config.json || error "Could not create config file." 109
        }
        main "$@"
      env:
        VERSION: ${{ inputs.version }}
        CHECKSUM: ${{ inputs.checksum }}
