name: 'Teleport connect action'
description: 'This action connects to a given kubernetes cluster through a given teleport proxy'
inputs:
  teleport_proxy:
    type: string
    description: The teleport proxy to connect to
    required: true
  teleport_kubernetes_cluster:
    type: string
    description: The kubernetes cluster to connect to
    required: true
  teleport_version:
    type: string
    description: The kubernetes cluster to connect to
    required: false
    default: 15.2.5

runs:
  using: 'composite'
  steps:
    - name: "Install Teleport"
      uses: teleport-actions/setup@v1
      with:
        version: ${{ inputs.teleport_version }}

    - name: "Teleport Authentication"
      uses: teleport-actions/auth-k8s@v1
      id: "teleport-auth"
      with:
        proxy: ${{ inputs.teleport_proxy }}
        token: github-token
        certificate-ttl: 1h
        kubernetes-cluster: ${{ inputs.teleport_kubernetes_cluster }}
