name: "[on_pr] Actionlint"

on:
  pull_request:

permissions:
  contents: "read"

jobs:
  actionlint:
    name: "actionlint"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "Install actionlint"
        run: |
          curl -sSL -o actionlint.tar.gz "https://github.com/pass-culture/actionlint/releases/download/v${VERSION}/actionlint_${VERSION}_linux_amd64.tar.gz"
          tar -zxvf actionlint.tar.gz && rm actionlint.tar.gz
          ./actionlint ./*/*.yml
        shell: bash
        env:
          VERSION: "0.2"